# Generated by Django 6.0.3 on 2026-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='notes/')),
            ],
        ),
    ]
