# Generated by Django 6.0.3 on 2026-03-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='module',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
